gen:
	go run main.go -d ./input/input.json

gen1:
	go run main.go -d ./input/input1.json

pos:
	go run main.go -d ./input/pos.json

new:
	go run main.go -d ./input/new.json
new1:
	go run main.go -d ./input/new1.json

split:
	go run main.go -d ./input/split.json

fiai:
	go run main.go -d ./input/fiai.json

kvencode:
	go run main.go -d ./input/kvencode.json

bala:
	go run main.go -d ./input/balaMain.json